const { stream } = require("exceljs");

const excelSheetColumn = [
  {
    header: "Asset_Id",
    key: "Asset_Id",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Asset Code",
    key: "AssetCode",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Original Asset Code",
    key: "Original_Asset_Code",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Asset Code as per Client system",
    key: "AssetCodeOnClient",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Entity",
    key: "EntityName",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Country",
    key: "Country",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "State",
    key: "State",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "City",
    key: "City",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Office Name",
    key: "OfficeName",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Department",
    key: "DepartmentName",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Floor",
    key: "Floor",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Unit Status",
    key: "Unit_Status",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Asset Group",
    key: "AssetGroupName",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Asset Sub Group",
    key: "AssetSubGroupName",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  { header: "Asset Description", key: "AssetDescription", width: 30 },
  {
    header: "Quantity",
    key: "Quantity",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Manufacturer",
    key: "Manufacturer",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Model Number",
    key: "ModelNumber",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Bond Number",
    key: "BondNumber",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Serial Number",
    key: "SerialNumber",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Type of Asset",
    key: "Type_Of_Asset",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Taggable/Non Taggable",
    key: "TaggableNotTaggable",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Movable/ImMovable",
    key: "CategoryofAsset",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Vendor Name",
    key: "VendorName",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "PO Number",
    key: "PoNumber",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "PO Date",
    key: "PoDate",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "PO Quantity",
    key: "PoQuantity",
    width: 25,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "GRN",
    key: "GRN",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "GRN Date",
    key: "GRNDate",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "GRN Quantity",
    key: "GRNQuantity",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Invoice Number",
    key: "InvoiceNumber",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Date Of Invoice",
    key: "DateOfInvoice",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Date Of Capitalization",
    key: "DateOfCapitalisation",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Status",
    key: "Status",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Warranty",
    key: "Warranty",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Warranty_Expiry_Date",
    key: "Warranty_Expiry_Date",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Asset Owner",
    key: "AssetAllocatedTo",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Base Price (₹)",
    key: "NetAmount",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "IGST",
    key: "IGST",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "IGST Amount",
    key: "IGSTAmount",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "CGST",
    key: "CGST",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "CGST Amount",
    key: "CGSTAmount",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "SGST",
    key: "SGST",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "SGST Amount",
    key: "SGSTAmount",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "VAT",
    key: "VAT",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "VAT Amount",
    key: "VATAmount",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Other Taxes",
    key: "OtherTaxes",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Other Taxes Amount",
    key: "OtherTaxesAmount",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Gross Amount",
    key: "GrossAmount",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Tax Credit",
    key: "TaxCredit",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Transferred Entity",
    key: "TransferredEntity",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Transferred OfficeName",
    key: "TransferredOfficeName",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Transferred Department",
    key: "TransferredDepartment",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Quantity",
    key: "Quantity1",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Transferred Date",
    key: "ApprovalDate1",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Transfer Value",
    key: "TransferValue",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "IGST",
    key: "IGST1",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "CGST",
    key: "CGST1",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "SGST",
    key: "SGST1",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "VAT",
    key: "VAT1",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "IGST Amount",
    key: "IGSTAmount1",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "SGST Amount",
    key: "SGSTAmount1",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "CGST Amount",
    key: "CGSTAmount1",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "VAT Amount",
    key: "VATAmount1",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Gross Amount",
    key: "GrossAmount1",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Vendor Name",
    key: "VendorName2",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Quantity",
    key: "Quantity2",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Sale Value",
    key: "SaleValue",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Sale Date",
    key: "ApprovalDate2",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "IGST",
    key: "IGST2",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "CGST",
    key: "CGST2",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "SGST",
    key: "SGST2",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "VAT",
    key: "VAT2",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "IGST Amount",
    key: "IGSTAmount2",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "SGST Amount",
    key: "SGSTAmount2",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "CGST Amount",
    key: "CGSTAmount2",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "VAT Amount",
    key: "VATAmount2",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
  {
    header: "Gross Amount",
    key: "GrossAmount2",
    width: 20,
    style: { alignment: { wrapText: true } },
  },
];

const setUpExcelLayout = (filename) => {
  const options = {
    filename,
    useStyles: true,
    useSharedStrings: true,
  };
  const workbook = new stream.xlsx.WorkbookWriter(options);
  const AssetSheet = workbook.addWorksheet("Asset Sheet");
  AssetSheet.columns = excelSheetColumn;
  [
    "A1",
    "B1",
    "C1",
    "D1",
    "E1",
    "F1",
    "G1",
    "H1",
    "I1",
    "J1",
    "K1",
    "L1",
    "M1",
    "N1",
    "O1",
    "P1",
    "Q1",
    "R1",
    "S1",
    "T1",
    "U1",
    "V1",
    "W1",
    "X1",
    "Y1",
    "Z1",
    "AA1",
    "AB1",
    "AC1",
    "AD1",
    "AE1",
    "AF1",
    "AG1",
    "AH1",
    "AI1",
    "AJ1",
    "AK1",
    "AL1",
    "AM1",
    "AN1",
    "AO1",
    "AP1",
    "AQ1",
    "AR1",
    "AS1",
    "AT1",
    "AU1",
    "AV1",
    "AW1",
    "AX1",
    "AY1",
    "AZ1",
    "BA1",
    "BB1",
    "BC1",
    "BD1",
    "BE1",
    "BF1",
    "BG1",
    "BH1",
    "BI1",
    "BJ1",
    "BK1",
    "BL1",
    "BM1",
    "BN1",
    "BO1",
    "BP1",
    "BQ1",
    "BR1",
    "BS1",
    "BT1",
    "BU1",
    "BV1",
    "BW1",
    "BX1",
    "BY1",
    "BZ1",
  ].map((key) => {
    AssetSheet.getCell(key).fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "D3D3D3" },
    };
    AssetSheet.getCell(key).border = {
      top: { style: "thin", color: { argb: "050505" } },
      left: { style: "thin", color: { argb: "050505" } },
      bottom: { style: "thin", color: { argb: "050505" } },
      right: { style: "thin", color: { argb: "050505" } },
    };
    AssetSheet.getCell(key).alignment = {
      vertical: "bottom",
      horizontal: "center",
    };
  });

  return { workbook, AssetSheet };
};

module.exports = {
  setUpExcelLayout,
  excelSheetColumn,
};
